ci: update github actions
Signed-off-by: fc-santos <filipesantos@live.ca>

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -11,14 +11,12 @@ on:
     branches: [main]
     paths:
       - app/**
-      - bifold
       - .yarn/**
       - .github/workflows/**
   pull_request:
     branches: [main]
     paths:
       - app/**
-      - bifold
       - .yarn/**
       - .github/workflows/**
       - .gitmodules
@@ -28,41 +26,60 @@ on:
       - .yarn/**
 
 jobs:
-  check-android-secrets:
+  check-secrets:
     runs-on: ubuntu-22.04
-    outputs:
-      isReleaseBuild: ${{ steps.isReleaseBuild.outputs.defined }}
     steps:
-      - id: isReleaseBuild
-        if: env.PLAY_STORE_JKS_BASE64 != null && env.PLAY_STORE_JKS_ALIAS != null && env.PLAY_STORE_JKS_PASSWD != null
-        run: echo "::set-output name=defined::true"
-        env:
-          PLAY_STORE_JKS_BASE64: ${{ secrets.PLAY_STORE_JKS_BASE64 }}
-          PLAY_STORE_JKS_ALIAS: ${{ secrets.PLAY_STORE_JKS_ALIAS }}
-          PLAY_STORE_JKS_PASSWD: ${{ secrets.PLAY_STORE_JKS_PASSWD }}
-
-  check-ios-secrets:
-    runs-on: ubuntu-22.04
-    outputs:
-      isReleaseBuild: ${{ steps.isReleaseBuild.outputs.defined }}
-    steps:
-      - id: isReleaseBuild
-        if: env.CERTIFICATE != null && env.KEYCHIAN_PASSWD != null && env.PROVISIONING_PROFILE != null
-        run: echo "::set-output name=defined::true"
+      - name: Check secrets
+        shell: bash
+        run: |
+          required_env_vars=(
+            "CERTIFICATE"
+            "KEYCHIAN_PASSWD"
+            "PROVISIONING_PROFILE"
+            "PLAY_STORE_JKS_BASE64"
+            "PLAY_STORE_JSK_ALIAS"
+            "PLAY_STORE_JKS_PASSWD"
+          )
+          for var in "${required_env_vars[@]}"; do
+            if [ -z "${!var}" ]; then
+              echo "error: $var is not set."
+              exit 1
+            fi
+          done
         env:
           CERTIFICATE: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
           KEYCHIAN_PASSWD: ${{ secrets.KEYCHIAN_PASSWD }}
           PROVISIONING_PROFILE: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
+          PLAY_STORE_JKS_BASE64: ${{ secrets.PLAY_STORE_JKS_BASE64 }}
+          PLAY_STORE_JKS_ALIAS: ${{ secrets.PLAY_STORE_JKS_ALIAS }}
+          PLAY_STORE_JKS_PASSWD: ${{ secrets.PLAY_STORE_JKS_PASSWD }}
+  check-vars:
+    runs-on: ubuntu-22.04
+    steps:
+      - name: Check variables
+        shell: bash
+        run: |
+          required_env_vars=(
+            "OCA_URL"
+            "MEDIATOR_USE_PUSH_NOTIFICATIONS"
+          )
+          for var in "${required_env_vars[@]}"; do
+            if [ -z "${!var}" ]; then
+              echo "error: $var is not set."
+              exit 1
+            fi
+          done
+        env:
+          OCA_URL: ${{ vars.OCA_URL }}
+          MEDIATOR_USE_PUSH_NOTIFICATIONS: ${{vars.MEDIATOR_USE_PUSH_NOTIFICATIONS }}
 
   build-ios:
-    needs: [check-ios-secrets]
+    needs: [check-secrets, check-vars]
     runs-on: macos-13
-    env:
-      BUNDLE_GEMFILE: ${{ github.workspace }}/app/Gemfile
     steps:
       - uses: actions/checkout@v4
 
-      - uses: actions/setup-python@v4
+      - uses: actions/setup-python@v5
         with:
           python-version: "3.11"
 
@@ -81,7 +98,7 @@ jobs:
           sudo xcode-select -p
 
       - name: Cached pip dependencies
-        uses: actions/cache@v3
+        uses: actions/cache@v4
         id: pip-cache
         with:
           path: ~/.cache/pip
@@ -91,7 +108,7 @@ jobs:
 
       - name: Cache pod dependencies
         id: pod-cache
-        uses: actions/cache@v3
+        uses: actions/cache@v4
         with:
           path: |
             app/ios/Pods
@@ -103,7 +120,7 @@ jobs:
 
       - name: Restore cached derived data
         id: cache-dd-restore
-        uses: actions/cache/restore@v3
+        uses: actions/cache/restore@v4
         with:
           path: app/ios/xbuild/Build
           key: ${{ runner.os }}-dd-xcode
@@ -116,12 +133,11 @@ jobs:
 
       - name: Install iOS dependencies
         # if: steps.pod-cache.outputs.cache-hit != 'true' || steps.npm-cache.outputs.cache-hit != 'true'
-        working-directory: app/ios
+        working-directory: app
         run: |
-          bundle install --frozen --gemfile=${BUNDLE_GEMFILE} && \
-          pod install && \
+          yarn run ios:setup && \
           git status && \
-          git diff Podfile.lock
+          git diff ios/Podfile.lock
 
       - name: Bump Build No.
         working-directory: app/ios
@@ -135,106 +151,68 @@ jobs:
         # Actual environment variables are not being picked up
         # by the build so they're put into an .env file.
       - name: Create environment settings
-        if: env.CQEN_MEDIATOR_URL != null && env.OCA_URL != null && env.MCN_MEDIATOR_URL != null
+        # if: env.CQEN_MEDIATOR_URL != null && env.OCA_URL != null && env.MCN_MEDIATOR_URL != null
         working-directory: app
         env:
+          MEDIATOR_USE_PUSH_NOTIFICATIONS: ${{ vars.MEDIATOR_USE_PUSH_NOTIFICATIONS }}
           CQEN_MEDIATOR_URL: ${{ secrets.CQEN_MEDIATOR_URL }}
           MCN_MEDIATOR_URL: ${{ secrets.MCN_MEDIATOR_URL }}
           OCA_URL: ${{ vars.OCA_URL }}
         run: |
+          echo "MEDIATOR_USE_PUSH_NOTIFICATIONS=${MEDIATOR_USE_PUSH_NOTIFICATIONS}" >.env
           echo "CQEN_MEDIATOR_URL=${CQEN_MEDIATOR_URL}" >.env
           echo "MCN_MEDIATOR_URL=${MCN_MEDIATOR_URL}" >>.env
           echo "OCA_URL=${OCA_URL}" >>.env
 
-      - name: Set Push Notification Capability
-        working-directory: app/ios/AriesBifold
-        env:
-          MEDIATOR_USE_PUSH_NOTIFICATIONS: false
-          MEDIATOR_LABEL: Mediator
+      - name: Update APS environment
         run: |
-          mv DEVELOPMENT.AriesBifold.entitlements AriesBifold.entitlements
+          sed -i '' 's/development/production/g' app/ios/AriesBifold/AriesBifold.entitlements
+          cat app/ios/AriesBifold/AriesBifold.entitlements
 
-      # https://docs.github.com/en/actions/deployment/deploying-xcode-applications/installing-an-apple-certificate-on-macos-runners-for-xcode-development
-      - name: Create Provisioning Profile
-        if: github.ref_name == 'main' && needs.check-ios-secrets.outputs.isReleaseBuild == 'true'
-        env:
-          PROVISIONING_PROFILE: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
-        run: |
-          scripts/makepp.sh
+      - name: Create prod signing credentials
+        uses: ./.github/workflows/actions/create-ios-sig-creds
+        with:
+          certificate: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
+          certificate_password: ${{ secrets.KEYCHIAN_PASSWD }}
+          provisioning_profile: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
 
-      # https://docs.github.com/en/actions/deployment/deploying-xcode-applications/installing-an-apple-certificate-on-macos-runners-for-xcode-development
-      - name: Build Keychain
-        if: github.ref_name == 'main' && needs.check-ios-secrets.outputs.isReleaseBuild == 'true'
-        env:
-          CERTIFICATE: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
-        run: |
-          scripts/makekc.sh ${{ secrets.KEYCHIAN_PASSWD }}
-
-      - name: Release build
-        if: github.ref_name == 'main' && needs.check-ios-secrets.outputs.isReleaseBuild == 'true'
+      - name: Archive build
         working-directory: app/ios
         run: |
           xcodebuild \
           -workspace AriesBifold.xcworkspace \
           -scheme AriesBifold \
+          -allowProvisioningUpdates \
           -configuration Release \
-          -derivedDataPath xbuild \
           -xcconfig ../../release.xcconfig \
-          -archivePath AriesBifold.xcarchive \
+          -derivedDataPath xbuild \
+          -archivePath ../../AriesBifold.xcarchive \
           -sdk iphoneos \
           -verbose \
           archive
 
       - name: Save cache for derived data
         id: cache-dd-save
-        uses: actions/cache/save@v3
+        uses: actions/cache/save@v4
         with:
           path: app/ios/xbuild/Build
           key: ${{ steps.cache-dd-restore.outputs.cache-primary-key }}
 
-      - name: Archive & Sign
-        if: github.ref_name == 'main' && needs.check-ios-secrets.outputs.isReleaseBuild == 'true'
-        working-directory: app/ios
-        run: |
-          xcodebuild \
-          -exportArchive \
-          -archivePath AriesBifold.xcarchive \
-          -exportPath export \
-          -exportOptionsPlist ../../options.plist \
-          -verbose
-      
-      # https://blog.codemagic.io/app-store-connect-api-codemagic-cli-tools/
-      - name: Install Codemagic CLI Tools
-        if: github.ref_name == 'main' && needs.check-ios-secrets.outputs.isReleaseBuild == 'true'
-        run: |
-          pip3 install codemagic-cli-tools
+      - name: Export production archive
+        uses: ./.github/workflows/actions/export-ios-archive
+        with:
+          export_options: options.plist
+          ouput_artifact_ref: ios-artifact
 
       - name: Ship to iTunes
-        if: github.ref_name == 'main' && needs.check-ios-secrets.outputs.isReleaseBuild == 'true'
-        working-directory: app/ios
-        env:
-          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
-          APP_STORE_CONNECT_KEY_IDENTIFIER: ${{ secrets.APP_STORE_CONNECT_KEY_IDENTIFIER }}
-          APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY_95 }}
-          VERSION_CODE: ${{ env.appBuildNumber }}
-          VERSION_NAME: ${{ env.appBuildVersion }}
-        run: |
-          export PATH=$PATH:/Library/Frameworks/Python.framework/Versions/3.11/bin
-          app-store-connect publish \
-          --enable-package-validation \
-          --max-build-processing-wait 25 \
-          --testflight \
-          --beta-group "The Team" "IDIM Team" \
-          --whats-new "Release ${VERSION_NAME}-${GITHUB_RUN_NUMBER}"
-
-      - name: Upload iOS artifact
-        if: github.ref_name == 'main' && needs.check-ios-secrets.outputs.isReleaseBuild == 'true'
-        uses: actions/upload-artifact@v3
+        if: github.ref_name == 'main'
+        uses: ./.github/workflows/actions/ship-to-itunes
         with:
-          name: ios-artifact
-          path: app/ios/export/AriesBifold.ipa
-          if-no-files-found: error
-          retention-days: 7
+          app_store_connect_issuer_id: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
+          app_store_connect_key_identifier: ${{ secrets.APP_STORE_CONNECT_KEY_IDENTIFIER }}
+          app_store_connect_private_key: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY_95 }}
+          version_code: ${{ env.appBuildNumber }}
+          version_name: ${{ env.appBuildVersion }}
 
   build-android:
     needs: [check-android-secrets]
@@ -243,17 +221,17 @@ jobs:
       contents: read
       packages: write
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v4
 
-      - name: Pull & update submodules recursively
-        run: |
-          git submodule update --init --recursive
+      - uses: actions/setup-python@v5
+        with:
+          python-version: "3.11"
 
       - name: Setup NodeJS
         uses: ./.github/workflows/actions/setup-node
 
       - name: Setup Java
-        uses: actions/setup-java@v3
+        uses: actions/setup-java@v4
         with:
           distribution: "zulu"
           java-version: 11
@@ -270,19 +248,19 @@ jobs:
         # Actual environment variables are not being picked up
         # by the build so they're put into an .env file.
       - name: Create environment settings
-        if: env.CQEN_MEDIATOR_URL != null && env.OCA_URL != null && env.MCN_MEDIATOR_URL != null
         working-directory: app
         env:
+          MEDIATOR_USE_PUSH_NOTIFICATIONS: ${{ vars.MEDIATOR_USE_PUSH_NOTIFICATIONS }}
           CQEN_MEDIATOR_URL: ${{ secrets.CQEN_MEDIATOR_URL }}
           MCN_MEDIATOR_URL: ${{ secrets.MCN_MEDIATOR_URL }}
           OCA_URL: ${{ vars.OCA_URL }}
         run: |
+          echo "MEDIATOR_USE_PUSH_NOTIFICATIONS=${MEDIATOR_USE_PUSH_NOTIFICATIONS}" >.env
           echo "CQEN_MEDIATOR_URL=${CQEN_MEDIATOR_URL}" >.env
           echo "MCN_MEDIATOR_URL=${MCN_MEDIATOR_URL}" >>.env
           echo "OCA_URL=${OCA_URL}" >>.env
 
       - name: Create release keystore
-        #if: github.ref_name == 'main' && needs.check-android-secrets.outputs.isReleaseBuild == 'true'
         working-directory: app/android/app
         env:
           PLAY_STORE_JKS_BASE64: ${{ secrets.PLAY_STORE_JKS_BASE64 }}
@@ -303,7 +281,6 @@ jobs:
       #          ./gradlew --no-daemon bundleRelease
 
       - name: Android release build
-        #if: github.ref_name == 'main' && needs.check-android-secrets.outputs.isReleaseBuild == 'true'
         working-directory: app/android
         env:
           PLAY_STORE_JKS_ALIAS: ${{ secrets.PLAY_STORE_JKS_ALIAS }}
@@ -320,20 +297,22 @@ jobs:
       #        run: mvn deploy:deploy-file -s $GITHUB_WORKSPACE/settings.xml -DgroupId=com.github.bcgov -DartifactId=bc-wallet -Dclassifier=android -DrepositoryId=github -Durl=https://maven.pkg.github.com/$GITHUB_REPOSITORY -Dversion=${{ env.appBuildVersion }}.${{ env.appBuildNumber }} -DgeneratePom=false -Dpackaging=aab -Dfile=app/android/app/build/outputs/bundle/release/app-release.aab
       #        env:
       #          GITHUB_TOKEN: ${{ github.token }}
+
       - name: List Artifacts
-        #if: github.ref_name == 'main' && needs.check-android-secrets.outputs.isReleaseBuild == 'true'
         run: |
           find . -type f -name '*.apk'
+
       - name: Upload artifact
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v4
         with:
           name: android
           path: |
             app/android/app/build/outputs/bundle/release/app-release.aab
             app/android/app/build/outputs/apk/release/app-release.apk
+
       - name: Upload Android artifact
-        if: github.ref_name == 'main' && needs.check-android-secrets.outputs.isReleaseBuild == 'true'
-        uses: actions/upload-artifact@v3
+        if: github.ref_name == 'main' 
+        uses: actions/upload-artifact@v4
         with:
           name: android-artifact
           path: app/android/app/build/outputs/bundle/release/app-release.aab
@@ -341,13 +320,13 @@ jobs:
           retention-days: 7
 
       - name: Ship to Google Play
-        if: github.ref_name == 'main' && needs.check-android-secrets.outputs.isReleaseBuild == 'true'
+        if: github.ref_name == 'main'
         working-directory: app/
         env:
           GOOGLE_API_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_API_CREDENTIALS_BASE64 }}
           GOOGLE_API_CREDENTIALS: "api_keys.json"
-          ANDROID_PACKAGE_NAME: "ca.qc.gouv.portefeuillemobileqc"
           ANDROID_BUNDLE_PATH: "./android/app/build/outputs/bundle/release/app-release.aab"
+          ANDROID_PACKAGE_NAME: "ca.qc.gouv.portefeuillemobileqc"
           VERSION_CODE: ${{ env.appBuildNumber }}
           VERSION_NAME: ${{ env.appBuildVersion }}
         run: |
@@ -356,16 +335,7 @@ jobs:
           # when we updated to yarn we started getting an error with paths
           # and had to add `/android` to the path.
           echo "${GOOGLE_API_CREDENTIALS_BASE64}" | base64 -d >${GOOGLE_API_CREDENTIALS} && \
-          node ./deploy-to-playstore.js
-
-      - name: Upload Android artifact
-        if: github.ref_name == 'main' && needs.check-android-secrets.outputs.isReleaseBuild == 'true'
-        uses: actions/upload-artifact@v3
-        with:
-          name: android-artifact
-          path: app/android/app/build/outputs/bundle/release/app-release.aab
-          if-no-files-found: error
-          retention-days: 7
+          node ./deploy-to-playstore.js 
 
   release:
     if: github.ref_name == 'main' && needs.check-android-secrets.outputs.isReleaseBuild == 'true' && needs.check-ios-secrets.outputs.isReleaseBuild == 'true'
@@ -385,7 +355,7 @@ jobs:
             Dev Release.
 
   ship-to-lambdatest:
-    if: github.ref_name == 'main' && needs.check-android-secrets.outputs.isReleaseBuild == 'true' && needs.check-ios-secrets.outputs.isReleaseBuild == 'true'
+    if: github.ref_name == 'main' 
     needs: [build-ios, build-android]
     runs-on: ubuntu-22.04
     outputs:
