feat: check cicd vars
Signed-off-by: Jason C. Leach <jason.leach@fullboar.ca>

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -3,6 +3,8 @@ name: Native Build & Test
 env:
   appBuildNumber: ${{ github.run_number }}
   appBuildVersion: "1.0.12"
+  OCA_URL: https://raw.githubusercontent.com/bcgov/aries-oca-bundles/main/
+  PROOF_TEMPLATE_URL: https://raw.githubusercontent.com/bcgov/bc-wallet-mobile/proof-template-bundle
 
 on:
   workflow_dispatch:
@@ -57,25 +59,16 @@ jobs:
     runs-on: ubuntu-22.04
     steps:
       - name: Check environment variables
-        env:
-          MEDIATOR_URL: ${{ secrets.MEDIATOR_URL }}
-          IAS_PORTAL_URL: ${{ secrets.IAS_PORTAL_URL }}
-          IAS_AGENT_INVITE_URL: ${{ secrets.IAS_AGENT_INVITE_URL }}
-          OCA_URL: ${{ vars.OCA_URL }}
-          PROOF_TEMPLATE_URL: ${{ vars.PROOF_TEMPLATE_URL }}
+        shell: bash
         run: |
           required_env_vars=(
-            "MEDIATOR_URL"
-            "IAS_PORTAL_URL"
-            "IAS_AGENT_INVITE_URL"
             "OCA_URL"
             "PROOF_TEMPLATE_URL"
           )
-
           for var in "${required_env_vars[@]}"; do
-            if [[ -z "${!var}" ]]; then
-                echo "Environment variable $var is not set or is empty."
-                exit 1
+            if [ -z "${!var}" ]; then
+              echo "Error: $var is not set."
+              exit 1
             fi
           done
 
@@ -168,18 +161,16 @@ jobs:
         if: env.MEDIATOR_URL != null && env.IAS_PORTAL_URL != null && env.IAS_AGENT_INVITE_URL != null && env.OCA_URL != null && env.PROOF_TEMPLATE_URL != null
         working-directory: app
         env:
+          MEDIATOR_USE_PUSH_NOTIFICATIONS: false
           MEDIATOR_URL: ${{ secrets.MEDIATOR_URL }}
           IAS_PORTAL_URL: ${{ secrets.IAS_PORTAL_URL }}
           IAS_AGENT_INVITE_URL: ${{ secrets.IAS_AGENT_INVITE_URL }}
-          OCA_URL: ${{ vars.OCA_URL }}
-          MEDIATOR_USE_PUSH_NOTIFICATIONS: false
-          PROOF_TEMPLATE_URL: ${{ vars.PROOF_TEMPLATE_URL }}
         run: |
-          echo "MEDIATOR_URL=${MEDIATOR_URL}" >.env
+          echo "MEDIATOR_USE_PUSH_NOTIFICATIONS=${MEDIATOR_USE_PUSH_NOTIFICATIONS}" >.env
+          echo "MEDIATOR_URL=${MEDIATOR_URL}" >>.env
           echo "IAS_PORTAL_URL=${IAS_PORTAL_URL}" >>.env
           echo "IAS_AGENT_INVITE_URL=${IAS_AGENT_INVITE_URL}" >>.env
           echo "OCA_URL=${OCA_URL}" >>.env
-          echo "MEDIATOR_USE_PUSH_NOTIFICATIONS=${MEDIATOR_USE_PUSH_NOTIFICATIONS}" >>.env
           echo "PROOF_TEMPLATE_URL=${PROOF_TEMPLATE_URL}" >>.env
 
       - name: Archive build
@@ -313,8 +304,6 @@ jobs:
           MEDIATOR_URL: ${{ secrets.MEDIATOR_URL }}
           IAS_PORTAL_URL: ${{ secrets.IAS_PORTAL_URL }}
           IAS_AGENT_INVITE_URL: ${{ secrets.IAS_AGENT_INVITE_URL }}
-          OCA_URL: ${{ vars.OCA_URL }}
-          PROOF_TEMPLATE_URL: ${{ vars.PROOF_TEMPLATE_URL }}
         run: |
           echo "MEDIATOR_URL=${MEDIATOR_URL}" >.env
           echo "IAS_PORTAL_URL=${IAS_PORTAL_URL}" >>.env
